### ISSUE TITLE
Unify configure and configure_no_section

### ISSUE THREAD

**Issue by xeno1991** [kenbeese/DataProcessor#182]
# 問題点

- 違いはsectionの指定の仕方だけなので、処理が重複して無駄。
- .ini はまだしも、jsonやyamlだと階層が深いかもしれない

# 提案

- `--section`はドット`.` (or other separations)区切りで階層を表すようにする
- `--section`のデフォルト値は空白(root)
  - 今現在、`--section`のデフォルト値はないのに関数側でデフォルト引数設定してるから挙動がわかりにくい。

## 例

```yaml
# param.yml

calc:
  cmd: some_calc
  params:
    a: 1
    b: 2
plot:
  cmd: gnuplot
  args: ...
```

```bash
dpmanip configure param.yml --section="calc.params"
```

**Comment by kenbeese** [comment]
separatorは`:`がいいのでは？

**Comment by xeno1991** [comment]
> separatorは:がいいのでは？

why?

> sectionが空白時の各変数名は例の場合はcalc.parmas.aとかにするってこと？
> それとも名にも取得しない？

違います。上の例だと`calc.params`をnodeのconfigureの部分に突っ込むことになります。

```python
conf = yaml.load("example.yml")["calc"]["params"]
node["configure] = conf
```

要するに、次のようにかきたいんですよ。

```python
sections = section.split(":")
conf = parser.parse(conffilne)
while sec in sections:
  conf = conf[sec]  # secがなければなんかエラー出す
node["configure"] = conf
```

> それと確認ですが、yamlはセクションなくてもパースできるはずだよね？

できるのに現在の実装だと無理なので、変えたいという意図。jsonも。

**Comment by kenbeese** [comment]
>> separatorは:がいいのでは？
> why?

.`.`の使用はセクション名で許されてるし。
`:`のほうがini形式でもyaml形式でもseparatorになってるからいいかなと。

> 違います。上の例だとcalc.paramsをnodeのconfigureの部分に突っ込むことになります。

sectionのデフォルト空白にしたとして
ini形式の読み込みのデフォルト動作はどうするの？って質問だった(;´･ω･)

**Comment by xeno1991** [comment]
> .の使用はセクション名で許されてるし。
> :のほうがini形式でもyaml形式でもseparatorになってるからいいかなと。

おｋ

> sectionのデフォルト空白にしたとして
> ini形式の読み込みのデフォルト動作はどうするの？って質問だった(;´･ω･)

`configure_no_section`と同じ動作になるんじゃないですかね

**Comment by kenbeese** [comment]
> configure_no_sectionと同じ動作になるんじゃないですかね

ini形式の場合、sectionは必須なので、`configure_no_section`と同じ動作にすると以下のような場合にまずいと思う。  

```ini
[foo]
foo=3
[bar]
foo=4
```

これは現状の仕様がよくないのが原因です。
sectionがある場合のconfigureの読み取りの仕様をしっかり決めないと、この辺はどの形式でも問題になります。
例えば、以下のyamlの場合で`dpmanip configure hoge.yaml --section foo`, `dpmanip configure hoge.yaml --section bar`と実行した場合どうする?ってこと。

```yaml
foo:
  foo: 3
bar: 
  foo: 4
```

この辺の仕様を決めないといけませんね。

## 仕様案

1. sectionで分かれてる場合はセクション指定と同様にする
   - メリット
      - 変更点少ない
   - デメリット
      - 変数名が長くなる
   - 上記の場合は`node["configure"] = { "foo:foo": 3, "bar:foo": 4}`
2. configureに階層的な辞書を許す
   - メリット
      - 階層構造そのまま
   - デメリット
      - 実装の変更が多くなる
   - 上記の場合は`node["configure"] = {"foo": {"foo": 3}, "bar": { "foo": 4}}`

**Comment by xeno1991** [comment]
あーその場合，`configure={}`になると思ってました．

階層を反映させたほうがいいような気がしてきました．そうすれば，パラメータが次のように書くことができます:

```yaml
parameters:
  initial_condition:
    input: initcond.txt
    ...
  boundary_condition:
    type: Dirichlet
    ...  
other_conf:
  (^p^)
```

webappで階層ごと表示/非表示にしたらよさそう．

階層の情報を使うのであれば 2. にしたほうがいいかと思います．
